### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by torwald-sergesson** [zimash/libvirter#6]
Maybe, it's worth to split our QEMUVM structure into separate parts. I see three global types here:
- virtual machine (VM)
- VMConnection or VMDriver
- VMManager

**VM** - is simple structure containing following information:
- type (qemu, kvm and so on)
- name
- CPU count
- memory size
- disk size

**VMConnection** - structure which performs main operations specific for concrete VM type. Can share some code between different connection types. Responsible for communication with virt.
Methods:
- Connect() error
- Disconnect() error
- Connected() bool
- Create(vm VM) error
- Delete(vm VM) error
- Start(vm VM) error
- Stop(vm VM) error
- and other like Action(vm VM) error. 
It assumes that it received a proper VM and must not check it's type.
Has specific constructors for specific type for instance: `NewQEMUConnection(url string)`
It's not clear if connection need logs or errors are enough, but it maybe need them.

**VMManager** - performs high level logic e.g. choosing proper connection according machine type, close and open them. Also manager writes logs. Shall have following methods:
- Create(vm VM) error
- Delete(vm VM) error
...
Has one constructor which accepts only config object and logger. 
`NewVMManager(config VMManagerConfig, logger *log.Logger) *VMManager`
Config shall contain information about available VM types, flavors definitions and connection settings (URLs, timeouts). On start can be just empty structure.

This way we can test them separately.

**Comment by zimash** [comment]
All minor comments in this PR for the future remember.
